clc
close all
clear

files = {'field_PlotPotential','potential_SphereGrad_test',...
    'potential_attractive','potential_attractiveGrad','potential_planner',...
    'potential_planner_test','potential_repulsiveSphere','potential_repulsiveSphereGrad',...
    'potential_total','potential_totalGrad','sphere_distance','twolink_jacobianMatrix',...
    'twolink_jacobian_test','twolink_planner_test','twolink_potential_total','twolink_potential_totalGrad'
    };

matlabStyleHinter(files)